// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/intelligencerun"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/objects"
)

// IntelligenceRunUpdate is the builder for updating IntelligenceRun entities.
type IntelligenceRunUpdate struct {
	config
	hooks     []Hook
	mutation  *IntelligenceRunMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the IntelligenceRunUpdate builder.
func (_u *IntelligenceRunUpdate) Where(ps ...predicate.IntelligenceRun) *IntelligenceRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IntelligenceRunUpdate) SetUpdatedAt(v time.Time) *IntelligenceRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IntelligenceRunUpdate) SetDeletedAt(v int) *IntelligenceRunUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableDeletedAt(v *int) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *IntelligenceRunUpdate) AddDeletedAt(v int) *IntelligenceRunUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetChannelName sets the "channel_name" field.
func (_u *IntelligenceRunUpdate) SetChannelName(v string) *IntelligenceRunUpdate {
	_u.mutation.SetChannelName(v)
	return _u
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableChannelName(v *string) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetChannelName(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *IntelligenceRunUpdate) SetModelID(v string) *IntelligenceRunUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableModelID(v *string) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *IntelligenceRunUpdate) SetTrigger(v string) *IntelligenceRunUpdate {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableTrigger(v *string) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IntelligenceRunUpdate) SetStatus(v intelligencerun.Status) *IntelligenceRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableStatus(v *intelligencerun.Status) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalKeys sets the "total_keys" field.
func (_u *IntelligenceRunUpdate) SetTotalKeys(v int) *IntelligenceRunUpdate {
	_u.mutation.ResetTotalKeys()
	_u.mutation.SetTotalKeys(v)
	return _u
}

// SetNillableTotalKeys sets the "total_keys" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableTotalKeys(v *int) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetTotalKeys(*v)
	}
	return _u
}

// AddTotalKeys adds value to the "total_keys" field.
func (_u *IntelligenceRunUpdate) AddTotalKeys(v int) *IntelligenceRunUpdate {
	_u.mutation.AddTotalKeys(v)
	return _u
}

// SetSuccessKeys sets the "success_keys" field.
func (_u *IntelligenceRunUpdate) SetSuccessKeys(v int) *IntelligenceRunUpdate {
	_u.mutation.ResetSuccessKeys()
	_u.mutation.SetSuccessKeys(v)
	return _u
}

// SetNillableSuccessKeys sets the "success_keys" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableSuccessKeys(v *int) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetSuccessKeys(*v)
	}
	return _u
}

// AddSuccessKeys adds value to the "success_keys" field.
func (_u *IntelligenceRunUpdate) AddSuccessKeys(v int) *IntelligenceRunUpdate {
	_u.mutation.AddSuccessKeys(v)
	return _u
}

// SetFailedKeys sets the "failed_keys" field.
func (_u *IntelligenceRunUpdate) SetFailedKeys(v int) *IntelligenceRunUpdate {
	_u.mutation.ResetFailedKeys()
	_u.mutation.SetFailedKeys(v)
	return _u
}

// SetNillableFailedKeys sets the "failed_keys" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableFailedKeys(v *int) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetFailedKeys(*v)
	}
	return _u
}

// AddFailedKeys adds value to the "failed_keys" field.
func (_u *IntelligenceRunUpdate) AddFailedKeys(v int) *IntelligenceRunUpdate {
	_u.mutation.AddFailedKeys(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *IntelligenceRunUpdate) SetDurationMs(v int) *IntelligenceRunUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *IntelligenceRunUpdate) SetNillableDurationMs(v *int) *IntelligenceRunUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *IntelligenceRunUpdate) AddDurationMs(v int) *IntelligenceRunUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetResults sets the "results" field.
func (_u *IntelligenceRunUpdate) SetResults(v []objects.IntelligenceKeyResult) *IntelligenceRunUpdate {
	_u.mutation.SetResults(v)
	return _u
}

// AppendResults appends value to the "results" field.
func (_u *IntelligenceRunUpdate) AppendResults(v []objects.IntelligenceKeyResult) *IntelligenceRunUpdate {
	_u.mutation.AppendResults(v)
	return _u
}

// ClearResults clears the value of the "results" field.
func (_u *IntelligenceRunUpdate) ClearResults() *IntelligenceRunUpdate {
	_u.mutation.ClearResults()
	return _u
}

// Mutation returns the IntelligenceRunMutation object of the builder.
func (_u *IntelligenceRunUpdate) Mutation() *IntelligenceRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IntelligenceRunUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntelligenceRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IntelligenceRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntelligenceRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntelligenceRunUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if intelligencerun.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized intelligencerun.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := intelligencerun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntelligenceRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := intelligencerun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IntelligenceRun.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *IntelligenceRunUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *IntelligenceRunUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *IntelligenceRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intelligencerun.Table, intelligencerun.Columns, sqlgraph.NewFieldSpec(intelligencerun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(intelligencerun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(intelligencerun.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(intelligencerun.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChannelName(); ok {
		_spec.SetField(intelligencerun.FieldChannelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(intelligencerun.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(intelligencerun.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(intelligencerun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TotalKeys(); ok {
		_spec.SetField(intelligencerun.FieldTotalKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalKeys(); ok {
		_spec.AddField(intelligencerun.FieldTotalKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessKeys(); ok {
		_spec.SetField(intelligencerun.FieldSuccessKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessKeys(); ok {
		_spec.AddField(intelligencerun.FieldSuccessKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedKeys(); ok {
		_spec.SetField(intelligencerun.FieldFailedKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedKeys(); ok {
		_spec.AddField(intelligencerun.FieldFailedKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(intelligencerun.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(intelligencerun.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Results(); ok {
		_spec.SetField(intelligencerun.FieldResults, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResults(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, intelligencerun.FieldResults, value)
		})
	}
	if _u.mutation.ResultsCleared() {
		_spec.ClearField(intelligencerun.FieldResults, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intelligencerun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IntelligenceRunUpdateOne is the builder for updating a single IntelligenceRun entity.
type IntelligenceRunUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *IntelligenceRunMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IntelligenceRunUpdateOne) SetUpdatedAt(v time.Time) *IntelligenceRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IntelligenceRunUpdateOne) SetDeletedAt(v int) *IntelligenceRunUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableDeletedAt(v *int) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *IntelligenceRunUpdateOne) AddDeletedAt(v int) *IntelligenceRunUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetChannelName sets the "channel_name" field.
func (_u *IntelligenceRunUpdateOne) SetChannelName(v string) *IntelligenceRunUpdateOne {
	_u.mutation.SetChannelName(v)
	return _u
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableChannelName(v *string) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetChannelName(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *IntelligenceRunUpdateOne) SetModelID(v string) *IntelligenceRunUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableModelID(v *string) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *IntelligenceRunUpdateOne) SetTrigger(v string) *IntelligenceRunUpdateOne {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableTrigger(v *string) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IntelligenceRunUpdateOne) SetStatus(v intelligencerun.Status) *IntelligenceRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableStatus(v *intelligencerun.Status) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalKeys sets the "total_keys" field.
func (_u *IntelligenceRunUpdateOne) SetTotalKeys(v int) *IntelligenceRunUpdateOne {
	_u.mutation.ResetTotalKeys()
	_u.mutation.SetTotalKeys(v)
	return _u
}

// SetNillableTotalKeys sets the "total_keys" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableTotalKeys(v *int) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetTotalKeys(*v)
	}
	return _u
}

// AddTotalKeys adds value to the "total_keys" field.
func (_u *IntelligenceRunUpdateOne) AddTotalKeys(v int) *IntelligenceRunUpdateOne {
	_u.mutation.AddTotalKeys(v)
	return _u
}

// SetSuccessKeys sets the "success_keys" field.
func (_u *IntelligenceRunUpdateOne) SetSuccessKeys(v int) *IntelligenceRunUpdateOne {
	_u.mutation.ResetSuccessKeys()
	_u.mutation.SetSuccessKeys(v)
	return _u
}

// SetNillableSuccessKeys sets the "success_keys" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableSuccessKeys(v *int) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetSuccessKeys(*v)
	}
	return _u
}

// AddSuccessKeys adds value to the "success_keys" field.
func (_u *IntelligenceRunUpdateOne) AddSuccessKeys(v int) *IntelligenceRunUpdateOne {
	_u.mutation.AddSuccessKeys(v)
	return _u
}

// SetFailedKeys sets the "failed_keys" field.
func (_u *IntelligenceRunUpdateOne) SetFailedKeys(v int) *IntelligenceRunUpdateOne {
	_u.mutation.ResetFailedKeys()
	_u.mutation.SetFailedKeys(v)
	return _u
}

// SetNillableFailedKeys sets the "failed_keys" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableFailedKeys(v *int) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetFailedKeys(*v)
	}
	return _u
}

// AddFailedKeys adds value to the "failed_keys" field.
func (_u *IntelligenceRunUpdateOne) AddFailedKeys(v int) *IntelligenceRunUpdateOne {
	_u.mutation.AddFailedKeys(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *IntelligenceRunUpdateOne) SetDurationMs(v int) *IntelligenceRunUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *IntelligenceRunUpdateOne) SetNillableDurationMs(v *int) *IntelligenceRunUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *IntelligenceRunUpdateOne) AddDurationMs(v int) *IntelligenceRunUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetResults sets the "results" field.
func (_u *IntelligenceRunUpdateOne) SetResults(v []objects.IntelligenceKeyResult) *IntelligenceRunUpdateOne {
	_u.mutation.SetResults(v)
	return _u
}

// AppendResults appends value to the "results" field.
func (_u *IntelligenceRunUpdateOne) AppendResults(v []objects.IntelligenceKeyResult) *IntelligenceRunUpdateOne {
	_u.mutation.AppendResults(v)
	return _u
}

// ClearResults clears the value of the "results" field.
func (_u *IntelligenceRunUpdateOne) ClearResults() *IntelligenceRunUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// Mutation returns the IntelligenceRunMutation object of the builder.
func (_u *IntelligenceRunUpdateOne) Mutation() *IntelligenceRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the IntelligenceRunUpdate builder.
func (_u *IntelligenceRunUpdateOne) Where(ps ...predicate.IntelligenceRun) *IntelligenceRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IntelligenceRunUpdateOne) Select(field string, fields ...string) *IntelligenceRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IntelligenceRun entity.
func (_u *IntelligenceRunUpdateOne) Save(ctx context.Context) (*IntelligenceRun, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntelligenceRunUpdateOne) SaveX(ctx context.Context) *IntelligenceRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IntelligenceRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntelligenceRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntelligenceRunUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if intelligencerun.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized intelligencerun.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := intelligencerun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntelligenceRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := intelligencerun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IntelligenceRun.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *IntelligenceRunUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *IntelligenceRunUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *IntelligenceRunUpdateOne) sqlSave(ctx context.Context) (_node *IntelligenceRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intelligencerun.Table, intelligencerun.Columns, sqlgraph.NewFieldSpec(intelligencerun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IntelligenceRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, intelligencerun.FieldID)
		for _, f := range fields {
			if !intelligencerun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != intelligencerun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(intelligencerun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(intelligencerun.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(intelligencerun.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChannelName(); ok {
		_spec.SetField(intelligencerun.FieldChannelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(intelligencerun.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(intelligencerun.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(intelligencerun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TotalKeys(); ok {
		_spec.SetField(intelligencerun.FieldTotalKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalKeys(); ok {
		_spec.AddField(intelligencerun.FieldTotalKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessKeys(); ok {
		_spec.SetField(intelligencerun.FieldSuccessKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessKeys(); ok {
		_spec.AddField(intelligencerun.FieldSuccessKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedKeys(); ok {
		_spec.SetField(intelligencerun.FieldFailedKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedKeys(); ok {
		_spec.AddField(intelligencerun.FieldFailedKeys, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(intelligencerun.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(intelligencerun.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Results(); ok {
		_spec.SetField(intelligencerun.FieldResults, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResults(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, intelligencerun.FieldResults, value)
		})
	}
	if _u.mutation.ResultsCleared() {
		_spec.ClearField(intelligencerun.FieldResults, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &IntelligenceRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intelligencerun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
