// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/intelligencerun"
	"github.com/looplj/axonhub/internal/objects"
)

// IntelligenceRunCreate is the builder for creating a IntelligenceRun entity.
type IntelligenceRunCreate struct {
	config
	mutation *IntelligenceRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IntelligenceRunCreate) SetCreatedAt(v time.Time) *IntelligenceRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableCreatedAt(v *time.Time) *IntelligenceRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IntelligenceRunCreate) SetUpdatedAt(v time.Time) *IntelligenceRunCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableUpdatedAt(v *time.Time) *IntelligenceRunCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *IntelligenceRunCreate) SetDeletedAt(v int) *IntelligenceRunCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableDeletedAt(v *int) *IntelligenceRunCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *IntelligenceRunCreate) SetChannelID(v int) *IntelligenceRunCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetChannelName sets the "channel_name" field.
func (_c *IntelligenceRunCreate) SetChannelName(v string) *IntelligenceRunCreate {
	_c.mutation.SetChannelName(v)
	return _c
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableChannelName(v *string) *IntelligenceRunCreate {
	if v != nil {
		_c.SetChannelName(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *IntelligenceRunCreate) SetModelID(v string) *IntelligenceRunCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_c *IntelligenceRunCreate) SetReasoningEffort(v string) *IntelligenceRunCreate {
	_c.mutation.SetReasoningEffort(v)
	return _c
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableReasoningEffort(v *string) *IntelligenceRunCreate {
	if v != nil {
		_c.SetReasoningEffort(*v)
	}
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *IntelligenceRunCreate) SetTrigger(v string) *IntelligenceRunCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableTrigger(v *string) *IntelligenceRunCreate {
	if v != nil {
		_c.SetTrigger(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IntelligenceRunCreate) SetStatus(v intelligencerun.Status) *IntelligenceRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableStatus(v *intelligencerun.Status) *IntelligenceRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalKeys sets the "total_keys" field.
func (_c *IntelligenceRunCreate) SetTotalKeys(v int) *IntelligenceRunCreate {
	_c.mutation.SetTotalKeys(v)
	return _c
}

// SetNillableTotalKeys sets the "total_keys" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableTotalKeys(v *int) *IntelligenceRunCreate {
	if v != nil {
		_c.SetTotalKeys(*v)
	}
	return _c
}

// SetSuccessKeys sets the "success_keys" field.
func (_c *IntelligenceRunCreate) SetSuccessKeys(v int) *IntelligenceRunCreate {
	_c.mutation.SetSuccessKeys(v)
	return _c
}

// SetNillableSuccessKeys sets the "success_keys" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableSuccessKeys(v *int) *IntelligenceRunCreate {
	if v != nil {
		_c.SetSuccessKeys(*v)
	}
	return _c
}

// SetFailedKeys sets the "failed_keys" field.
func (_c *IntelligenceRunCreate) SetFailedKeys(v int) *IntelligenceRunCreate {
	_c.mutation.SetFailedKeys(v)
	return _c
}

// SetNillableFailedKeys sets the "failed_keys" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableFailedKeys(v *int) *IntelligenceRunCreate {
	if v != nil {
		_c.SetFailedKeys(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *IntelligenceRunCreate) SetDurationMs(v int) *IntelligenceRunCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *IntelligenceRunCreate) SetNillableDurationMs(v *int) *IntelligenceRunCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetResults sets the "results" field.
func (_c *IntelligenceRunCreate) SetResults(v []objects.IntelligenceKeyResult) *IntelligenceRunCreate {
	_c.mutation.SetResults(v)
	return _c
}

// Mutation returns the IntelligenceRunMutation object of the builder.
func (_c *IntelligenceRunCreate) Mutation() *IntelligenceRunMutation {
	return _c.mutation
}

// Save creates the IntelligenceRun in the database.
func (_c *IntelligenceRunCreate) Save(ctx context.Context) (*IntelligenceRun, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntelligenceRunCreate) SaveX(ctx context.Context) *IntelligenceRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntelligenceRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntelligenceRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntelligenceRunCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if intelligencerun.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized intelligencerun.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := intelligencerun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if intelligencerun.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized intelligencerun.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := intelligencerun.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := intelligencerun.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.ChannelName(); !ok {
		v := intelligencerun.DefaultChannelName
		_c.mutation.SetChannelName(v)
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		v := intelligencerun.DefaultReasoningEffort
		_c.mutation.SetReasoningEffort(v)
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		v := intelligencerun.DefaultTrigger
		_c.mutation.SetTrigger(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := intelligencerun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalKeys(); !ok {
		v := intelligencerun.DefaultTotalKeys
		_c.mutation.SetTotalKeys(v)
	}
	if _, ok := _c.mutation.SuccessKeys(); !ok {
		v := intelligencerun.DefaultSuccessKeys
		_c.mutation.SetSuccessKeys(v)
	}
	if _, ok := _c.mutation.FailedKeys(); !ok {
		v := intelligencerun.DefaultFailedKeys
		_c.mutation.SetFailedKeys(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := intelligencerun.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntelligenceRunCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "IntelligenceRun.deleted_at"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "IntelligenceRun.channel_id"`)}
	}
	if _, ok := _c.mutation.ChannelName(); !ok {
		return &ValidationError{Name: "channel_name", err: errors.New(`ent: missing required field "IntelligenceRun.channel_name"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "IntelligenceRun.model_id"`)}
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		return &ValidationError{Name: "reasoning_effort", err: errors.New(`ent: missing required field "IntelligenceRun.reasoning_effort"`)}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "IntelligenceRun.trigger"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IntelligenceRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := intelligencerun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IntelligenceRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalKeys(); !ok {
		return &ValidationError{Name: "total_keys", err: errors.New(`ent: missing required field "IntelligenceRun.total_keys"`)}
	}
	if _, ok := _c.mutation.SuccessKeys(); !ok {
		return &ValidationError{Name: "success_keys", err: errors.New(`ent: missing required field "IntelligenceRun.success_keys"`)}
	}
	if _, ok := _c.mutation.FailedKeys(); !ok {
		return &ValidationError{Name: "failed_keys", err: errors.New(`ent: missing required field "IntelligenceRun.failed_keys"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "IntelligenceRun.duration_ms"`)}
	}
	return nil
}

func (_c *IntelligenceRunCreate) sqlSave(ctx context.Context) (*IntelligenceRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntelligenceRunCreate) createSpec() (*IntelligenceRun, *sqlgraph.CreateSpec) {
	var (
		_node = &IntelligenceRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(intelligencerun.Table, sqlgraph.NewFieldSpec(intelligencerun.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(intelligencerun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(intelligencerun.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(intelligencerun.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(intelligencerun.FieldChannelID, field.TypeInt, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.ChannelName(); ok {
		_spec.SetField(intelligencerun.FieldChannelName, field.TypeString, value)
		_node.ChannelName = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(intelligencerun.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.ReasoningEffort(); ok {
		_spec.SetField(intelligencerun.FieldReasoningEffort, field.TypeString, value)
		_node.ReasoningEffort = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(intelligencerun.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(intelligencerun.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalKeys(); ok {
		_spec.SetField(intelligencerun.FieldTotalKeys, field.TypeInt, value)
		_node.TotalKeys = value
	}
	if value, ok := _c.mutation.SuccessKeys(); ok {
		_spec.SetField(intelligencerun.FieldSuccessKeys, field.TypeInt, value)
		_node.SuccessKeys = value
	}
	if value, ok := _c.mutation.FailedKeys(); ok {
		_spec.SetField(intelligencerun.FieldFailedKeys, field.TypeInt, value)
		_node.FailedKeys = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(intelligencerun.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.Results(); ok {
		_spec.SetField(intelligencerun.FieldResults, field.TypeJSON, value)
		_node.Results = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntelligenceRun.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntelligenceRunUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IntelligenceRunCreate) OnConflict(opts ...sql.ConflictOption) *IntelligenceRunUpsertOne {
	_c.conflict = opts
	return &IntelligenceRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntelligenceRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntelligenceRunCreate) OnConflictColumns(columns ...string) *IntelligenceRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntelligenceRunUpsertOne{
		create: _c,
	}
}

type (
	// IntelligenceRunUpsertOne is the builder for "upsert"-ing
	//  one IntelligenceRun node.
	IntelligenceRunUpsertOne struct {
		create *IntelligenceRunCreate
	}

	// IntelligenceRunUpsert is the "OnConflict" setter.
	IntelligenceRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelligenceRunUpsert) SetUpdatedAt(v time.Time) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateUpdatedAt() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IntelligenceRunUpsert) SetDeletedAt(v int) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateDeletedAt() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *IntelligenceRunUpsert) AddDeletedAt(v int) *IntelligenceRunUpsert {
	u.Add(intelligencerun.FieldDeletedAt, v)
	return u
}

// SetChannelName sets the "channel_name" field.
func (u *IntelligenceRunUpsert) SetChannelName(v string) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldChannelName, v)
	return u
}

// UpdateChannelName sets the "channel_name" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateChannelName() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldChannelName)
	return u
}

// SetModelID sets the "model_id" field.
func (u *IntelligenceRunUpsert) SetModelID(v string) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateModelID() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldModelID)
	return u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *IntelligenceRunUpsert) SetReasoningEffort(v string) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldReasoningEffort, v)
	return u
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateReasoningEffort() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldReasoningEffort)
	return u
}

// SetTrigger sets the "trigger" field.
func (u *IntelligenceRunUpsert) SetTrigger(v string) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldTrigger, v)
	return u
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateTrigger() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldTrigger)
	return u
}

// SetStatus sets the "status" field.
func (u *IntelligenceRunUpsert) SetStatus(v intelligencerun.Status) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateStatus() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldStatus)
	return u
}

// SetTotalKeys sets the "total_keys" field.
func (u *IntelligenceRunUpsert) SetTotalKeys(v int) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldTotalKeys, v)
	return u
}

// UpdateTotalKeys sets the "total_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateTotalKeys() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldTotalKeys)
	return u
}

// AddTotalKeys adds v to the "total_keys" field.
func (u *IntelligenceRunUpsert) AddTotalKeys(v int) *IntelligenceRunUpsert {
	u.Add(intelligencerun.FieldTotalKeys, v)
	return u
}

// SetSuccessKeys sets the "success_keys" field.
func (u *IntelligenceRunUpsert) SetSuccessKeys(v int) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldSuccessKeys, v)
	return u
}

// UpdateSuccessKeys sets the "success_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateSuccessKeys() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldSuccessKeys)
	return u
}

// AddSuccessKeys adds v to the "success_keys" field.
func (u *IntelligenceRunUpsert) AddSuccessKeys(v int) *IntelligenceRunUpsert {
	u.Add(intelligencerun.FieldSuccessKeys, v)
	return u
}

// SetFailedKeys sets the "failed_keys" field.
func (u *IntelligenceRunUpsert) SetFailedKeys(v int) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldFailedKeys, v)
	return u
}

// UpdateFailedKeys sets the "failed_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateFailedKeys() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldFailedKeys)
	return u
}

// AddFailedKeys adds v to the "failed_keys" field.
func (u *IntelligenceRunUpsert) AddFailedKeys(v int) *IntelligenceRunUpsert {
	u.Add(intelligencerun.FieldFailedKeys, v)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *IntelligenceRunUpsert) SetDurationMs(v int) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateDurationMs() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *IntelligenceRunUpsert) AddDurationMs(v int) *IntelligenceRunUpsert {
	u.Add(intelligencerun.FieldDurationMs, v)
	return u
}

// SetResults sets the "results" field.
func (u *IntelligenceRunUpsert) SetResults(v []objects.IntelligenceKeyResult) *IntelligenceRunUpsert {
	u.Set(intelligencerun.FieldResults, v)
	return u
}

// UpdateResults sets the "results" field to the value that was provided on create.
func (u *IntelligenceRunUpsert) UpdateResults() *IntelligenceRunUpsert {
	u.SetExcluded(intelligencerun.FieldResults)
	return u
}

// ClearResults clears the value of the "results" field.
func (u *IntelligenceRunUpsert) ClearResults() *IntelligenceRunUpsert {
	u.SetNull(intelligencerun.FieldResults)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IntelligenceRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IntelligenceRunUpsertOne) UpdateNewValues() *IntelligenceRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(intelligencerun.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ChannelID(); exists {
			s.SetIgnore(intelligencerun.FieldChannelID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntelligenceRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IntelligenceRunUpsertOne) Ignore() *IntelligenceRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntelligenceRunUpsertOne) DoNothing() *IntelligenceRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntelligenceRunCreate.OnConflict
// documentation for more info.
func (u *IntelligenceRunUpsertOne) Update(set func(*IntelligenceRunUpsert)) *IntelligenceRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntelligenceRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelligenceRunUpsertOne) SetUpdatedAt(v time.Time) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateUpdatedAt() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IntelligenceRunUpsertOne) SetDeletedAt(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *IntelligenceRunUpsertOne) AddDeletedAt(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateDeletedAt() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetChannelName sets the "channel_name" field.
func (u *IntelligenceRunUpsertOne) SetChannelName(v string) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetChannelName(v)
	})
}

// UpdateChannelName sets the "channel_name" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateChannelName() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateChannelName()
	})
}

// SetModelID sets the "model_id" field.
func (u *IntelligenceRunUpsertOne) SetModelID(v string) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateModelID() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateModelID()
	})
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *IntelligenceRunUpsertOne) SetReasoningEffort(v string) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetReasoningEffort(v)
	})
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateReasoningEffort() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateReasoningEffort()
	})
}

// SetTrigger sets the "trigger" field.
func (u *IntelligenceRunUpsertOne) SetTrigger(v string) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetTrigger(v)
	})
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateTrigger() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateTrigger()
	})
}

// SetStatus sets the "status" field.
func (u *IntelligenceRunUpsertOne) SetStatus(v intelligencerun.Status) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateStatus() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalKeys sets the "total_keys" field.
func (u *IntelligenceRunUpsertOne) SetTotalKeys(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetTotalKeys(v)
	})
}

// AddTotalKeys adds v to the "total_keys" field.
func (u *IntelligenceRunUpsertOne) AddTotalKeys(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddTotalKeys(v)
	})
}

// UpdateTotalKeys sets the "total_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateTotalKeys() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateTotalKeys()
	})
}

// SetSuccessKeys sets the "success_keys" field.
func (u *IntelligenceRunUpsertOne) SetSuccessKeys(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetSuccessKeys(v)
	})
}

// AddSuccessKeys adds v to the "success_keys" field.
func (u *IntelligenceRunUpsertOne) AddSuccessKeys(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddSuccessKeys(v)
	})
}

// UpdateSuccessKeys sets the "success_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateSuccessKeys() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateSuccessKeys()
	})
}

// SetFailedKeys sets the "failed_keys" field.
func (u *IntelligenceRunUpsertOne) SetFailedKeys(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetFailedKeys(v)
	})
}

// AddFailedKeys adds v to the "failed_keys" field.
func (u *IntelligenceRunUpsertOne) AddFailedKeys(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddFailedKeys(v)
	})
}

// UpdateFailedKeys sets the "failed_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateFailedKeys() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateFailedKeys()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *IntelligenceRunUpsertOne) SetDurationMs(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *IntelligenceRunUpsertOne) AddDurationMs(v int) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateDurationMs() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateDurationMs()
	})
}

// SetResults sets the "results" field.
func (u *IntelligenceRunUpsertOne) SetResults(v []objects.IntelligenceKeyResult) *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetResults(v)
	})
}

// UpdateResults sets the "results" field to the value that was provided on create.
func (u *IntelligenceRunUpsertOne) UpdateResults() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateResults()
	})
}

// ClearResults clears the value of the "results" field.
func (u *IntelligenceRunUpsertOne) ClearResults() *IntelligenceRunUpsertOne {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.ClearResults()
	})
}

// Exec executes the query.
func (u *IntelligenceRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntelligenceRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntelligenceRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IntelligenceRunUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IntelligenceRunUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IntelligenceRunCreateBulk is the builder for creating many IntelligenceRun entities in bulk.
type IntelligenceRunCreateBulk struct {
	config
	err      error
	builders []*IntelligenceRunCreate
	conflict []sql.ConflictOption
}

// Save creates the IntelligenceRun entities in the database.
func (_c *IntelligenceRunCreateBulk) Save(ctx context.Context) ([]*IntelligenceRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntelligenceRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntelligenceRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntelligenceRunCreateBulk) SaveX(ctx context.Context) []*IntelligenceRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntelligenceRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntelligenceRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntelligenceRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntelligenceRunUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IntelligenceRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *IntelligenceRunUpsertBulk {
	_c.conflict = opts
	return &IntelligenceRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntelligenceRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntelligenceRunCreateBulk) OnConflictColumns(columns ...string) *IntelligenceRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntelligenceRunUpsertBulk{
		create: _c,
	}
}

// IntelligenceRunUpsertBulk is the builder for "upsert"-ing
// a bulk of IntelligenceRun nodes.
type IntelligenceRunUpsertBulk struct {
	create *IntelligenceRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IntelligenceRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IntelligenceRunUpsertBulk) UpdateNewValues() *IntelligenceRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(intelligencerun.FieldCreatedAt)
			}
			if _, exists := b.mutation.ChannelID(); exists {
				s.SetIgnore(intelligencerun.FieldChannelID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntelligenceRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IntelligenceRunUpsertBulk) Ignore() *IntelligenceRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntelligenceRunUpsertBulk) DoNothing() *IntelligenceRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntelligenceRunCreateBulk.OnConflict
// documentation for more info.
func (u *IntelligenceRunUpsertBulk) Update(set func(*IntelligenceRunUpsert)) *IntelligenceRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntelligenceRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelligenceRunUpsertBulk) SetUpdatedAt(v time.Time) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateUpdatedAt() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IntelligenceRunUpsertBulk) SetDeletedAt(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *IntelligenceRunUpsertBulk) AddDeletedAt(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateDeletedAt() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetChannelName sets the "channel_name" field.
func (u *IntelligenceRunUpsertBulk) SetChannelName(v string) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetChannelName(v)
	})
}

// UpdateChannelName sets the "channel_name" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateChannelName() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateChannelName()
	})
}

// SetModelID sets the "model_id" field.
func (u *IntelligenceRunUpsertBulk) SetModelID(v string) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateModelID() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateModelID()
	})
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *IntelligenceRunUpsertBulk) SetReasoningEffort(v string) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetReasoningEffort(v)
	})
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateReasoningEffort() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateReasoningEffort()
	})
}

// SetTrigger sets the "trigger" field.
func (u *IntelligenceRunUpsertBulk) SetTrigger(v string) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetTrigger(v)
	})
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateTrigger() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateTrigger()
	})
}

// SetStatus sets the "status" field.
func (u *IntelligenceRunUpsertBulk) SetStatus(v intelligencerun.Status) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateStatus() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalKeys sets the "total_keys" field.
func (u *IntelligenceRunUpsertBulk) SetTotalKeys(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetTotalKeys(v)
	})
}

// AddTotalKeys adds v to the "total_keys" field.
func (u *IntelligenceRunUpsertBulk) AddTotalKeys(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddTotalKeys(v)
	})
}

// UpdateTotalKeys sets the "total_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateTotalKeys() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateTotalKeys()
	})
}

// SetSuccessKeys sets the "success_keys" field.
func (u *IntelligenceRunUpsertBulk) SetSuccessKeys(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetSuccessKeys(v)
	})
}

// AddSuccessKeys adds v to the "success_keys" field.
func (u *IntelligenceRunUpsertBulk) AddSuccessKeys(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddSuccessKeys(v)
	})
}

// UpdateSuccessKeys sets the "success_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateSuccessKeys() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateSuccessKeys()
	})
}

// SetFailedKeys sets the "failed_keys" field.
func (u *IntelligenceRunUpsertBulk) SetFailedKeys(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetFailedKeys(v)
	})
}

// AddFailedKeys adds v to the "failed_keys" field.
func (u *IntelligenceRunUpsertBulk) AddFailedKeys(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddFailedKeys(v)
	})
}

// UpdateFailedKeys sets the "failed_keys" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateFailedKeys() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateFailedKeys()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *IntelligenceRunUpsertBulk) SetDurationMs(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *IntelligenceRunUpsertBulk) AddDurationMs(v int) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateDurationMs() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateDurationMs()
	})
}

// SetResults sets the "results" field.
func (u *IntelligenceRunUpsertBulk) SetResults(v []objects.IntelligenceKeyResult) *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.SetResults(v)
	})
}

// UpdateResults sets the "results" field to the value that was provided on create.
func (u *IntelligenceRunUpsertBulk) UpdateResults() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.UpdateResults()
	})
}

// ClearResults clears the value of the "results" field.
func (u *IntelligenceRunUpsertBulk) ClearResults() *IntelligenceRunUpsertBulk {
	return u.Update(func(s *IntelligenceRunUpsert) {
		s.ClearResults()
	})
}

// Exec executes the query.
func (u *IntelligenceRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IntelligenceRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntelligenceRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntelligenceRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
