// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/intelligencerun"
	"github.com/looplj/axonhub/internal/objects"
)

// IntelligenceRun is the model entity for the IntelligenceRun schema.
type IntelligenceRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Channel this run evaluated
	ChannelID int `json:"channel_id,omitempty"`
	// Channel name captured at run time, so history survives a rename
	ChannelName string `json:"channel_name,omitempty"`
	// Model the channel was asked to generate with
	ModelID string `json:"model_id,omitempty"`
	// Thinking level requested for this run; empty when the provider default applied
	ReasoningEffort string `json:"reasoning_effort,omitempty"`
	// What started the run: manual or scheduled
	Trigger string `json:"trigger,omitempty"`
	// running while the check is in flight; then succeeded, partial or failed
	Status intelligencerun.Status `json:"status,omitempty"`
	// Number of API keys evaluated
	TotalKeys int `json:"total_keys,omitempty"`
	// Number of keys whose assessment succeeded
	SuccessKeys int `json:"success_keys,omitempty"`
	// Number of keys whose assessment failed
	FailedKeys int `json:"failed_keys,omitempty"`
	// Wall-clock duration of the whole run
	DurationMs int `json:"duration_ms,omitempty"`
	// Per-key outcomes, including the generated source
	Results      []objects.IntelligenceKeyResult `json:"results,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IntelligenceRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case intelligencerun.FieldResults:
			values[i] = new([]byte)
		case intelligencerun.FieldID, intelligencerun.FieldDeletedAt, intelligencerun.FieldChannelID, intelligencerun.FieldTotalKeys, intelligencerun.FieldSuccessKeys, intelligencerun.FieldFailedKeys, intelligencerun.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case intelligencerun.FieldChannelName, intelligencerun.FieldModelID, intelligencerun.FieldReasoningEffort, intelligencerun.FieldTrigger, intelligencerun.FieldStatus:
			values[i] = new(sql.NullString)
		case intelligencerun.FieldCreatedAt, intelligencerun.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IntelligenceRun fields.
func (_m *IntelligenceRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case intelligencerun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case intelligencerun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case intelligencerun.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case intelligencerun.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case intelligencerun.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case intelligencerun.FieldChannelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_name", values[i])
			} else if value.Valid {
				_m.ChannelName = value.String
			}
		case intelligencerun.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case intelligencerun.FieldReasoningEffort:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_effort", values[i])
			} else if value.Valid {
				_m.ReasoningEffort = value.String
			}
		case intelligencerun.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				_m.Trigger = value.String
			}
		case intelligencerun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = intelligencerun.Status(value.String)
			}
		case intelligencerun.FieldTotalKeys:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_keys", values[i])
			} else if value.Valid {
				_m.TotalKeys = int(value.Int64)
			}
		case intelligencerun.FieldSuccessKeys:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_keys", values[i])
			} else if value.Valid {
				_m.SuccessKeys = int(value.Int64)
			}
		case intelligencerun.FieldFailedKeys:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_keys", values[i])
			} else if value.Valid {
				_m.FailedKeys = int(value.Int64)
			}
		case intelligencerun.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = int(value.Int64)
			}
		case intelligencerun.FieldResults:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field results", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Results); err != nil {
					return fmt.Errorf("unmarshal field results: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IntelligenceRun.
// This includes values selected through modifiers, order, etc.
func (_m *IntelligenceRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IntelligenceRun.
// Note that you need to call IntelligenceRun.Unwrap() before calling this method if this IntelligenceRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IntelligenceRun) Update() *IntelligenceRunUpdateOne {
	return NewIntelligenceRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IntelligenceRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IntelligenceRun) Unwrap() *IntelligenceRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IntelligenceRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IntelligenceRun) String() string {
	var builder strings.Builder
	builder.WriteString("IntelligenceRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("channel_name=")
	builder.WriteString(_m.ChannelName)
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("reasoning_effort=")
	builder.WriteString(_m.ReasoningEffort)
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(_m.Trigger)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("total_keys=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalKeys))
	builder.WriteString(", ")
	builder.WriteString("success_keys=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessKeys))
	builder.WriteString(", ")
	builder.WriteString("failed_keys=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedKeys))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("results=")
	builder.WriteString(fmt.Sprintf("%v", _m.Results))
	builder.WriteByte(')')
	return builder.String()
}

// IntelligenceRuns is a parsable slice of IntelligenceRun.
type IntelligenceRuns []*IntelligenceRun
