// Code generated by ent, DO NOT EDIT.

package intelligencerun

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the intelligencerun type in the database.
	Label = "intelligence_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldChannelName holds the string denoting the channel_name field in the database.
	FieldChannelName = "channel_name"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldTrigger holds the string denoting the trigger field in the database.
	FieldTrigger = "trigger"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTotalKeys holds the string denoting the total_keys field in the database.
	FieldTotalKeys = "total_keys"
	// FieldSuccessKeys holds the string denoting the success_keys field in the database.
	FieldSuccessKeys = "success_keys"
	// FieldFailedKeys holds the string denoting the failed_keys field in the database.
	FieldFailedKeys = "failed_keys"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldResults holds the string denoting the results field in the database.
	FieldResults = "results"
	// Table holds the table name of the intelligencerun in the database.
	Table = "intelligence_runs"
)

// Columns holds all SQL columns for intelligencerun fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldChannelID,
	FieldChannelName,
	FieldModelID,
	FieldTrigger,
	FieldStatus,
	FieldTotalKeys,
	FieldSuccessKeys,
	FieldFailedKeys,
	FieldDurationMs,
	FieldResults,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultChannelName holds the default value on creation for the "channel_name" field.
	DefaultChannelName string
	// DefaultTrigger holds the default value on creation for the "trigger" field.
	DefaultTrigger string
	// DefaultTotalKeys holds the default value on creation for the "total_keys" field.
	DefaultTotalKeys int
	// DefaultSuccessKeys holds the default value on creation for the "success_keys" field.
	DefaultSuccessKeys int
	// DefaultFailedKeys holds the default value on creation for the "failed_keys" field.
	DefaultFailedKeys int
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int
)

// Status defines the type for the "status" enum field.
type Status string

// StatusFailed is the default value of the Status enum.
const DefaultStatus = StatusFailed

// Status values.
const (
	StatusSucceeded Status = "succeeded"
	StatusFailed    Status = "failed"
	StatusPartial   Status = "partial"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSucceeded, StatusFailed, StatusPartial:
		return nil
	default:
		return fmt.Errorf("intelligencerun: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the IntelligenceRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByChannelName orders the results by the channel_name field.
func ByChannelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelName, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByTrigger orders the results by the trigger field.
func ByTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrigger, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTotalKeys orders the results by the total_keys field.
func ByTotalKeys(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalKeys, opts...).ToFunc()
}

// BySuccessKeys orders the results by the success_keys field.
func BySuccessKeys(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessKeys, opts...).ToFunc()
}

// ByFailedKeys orders the results by the failed_keys field.
func ByFailedKeys(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedKeys, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}
