// Code generated by ent, DO NOT EDIT.

package intelligencerun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldDeletedAt, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldChannelID, v))
}

// ChannelName applies equality check predicate on the "channel_name" field. It's identical to ChannelNameEQ.
func ChannelName(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldChannelName, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldModelID, v))
}

// ReasoningEffort applies equality check predicate on the "reasoning_effort" field. It's identical to ReasoningEffortEQ.
func ReasoningEffort(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldReasoningEffort, v))
}

// Trigger applies equality check predicate on the "trigger" field. It's identical to TriggerEQ.
func Trigger(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldTrigger, v))
}

// TotalKeys applies equality check predicate on the "total_keys" field. It's identical to TotalKeysEQ.
func TotalKeys(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldTotalKeys, v))
}

// SuccessKeys applies equality check predicate on the "success_keys" field. It's identical to SuccessKeysEQ.
func SuccessKeys(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldSuccessKeys, v))
}

// FailedKeys applies equality check predicate on the "failed_keys" field. It's identical to FailedKeysEQ.
func FailedKeys(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldFailedKeys, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldDurationMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldDeletedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldChannelID, v))
}

// ChannelNameEQ applies the EQ predicate on the "channel_name" field.
func ChannelNameEQ(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldChannelName, v))
}

// ChannelNameNEQ applies the NEQ predicate on the "channel_name" field.
func ChannelNameNEQ(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldChannelName, v))
}

// ChannelNameIn applies the In predicate on the "channel_name" field.
func ChannelNameIn(vs ...string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldChannelName, vs...))
}

// ChannelNameNotIn applies the NotIn predicate on the "channel_name" field.
func ChannelNameNotIn(vs ...string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldChannelName, vs...))
}

// ChannelNameGT applies the GT predicate on the "channel_name" field.
func ChannelNameGT(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldChannelName, v))
}

// ChannelNameGTE applies the GTE predicate on the "channel_name" field.
func ChannelNameGTE(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldChannelName, v))
}

// ChannelNameLT applies the LT predicate on the "channel_name" field.
func ChannelNameLT(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldChannelName, v))
}

// ChannelNameLTE applies the LTE predicate on the "channel_name" field.
func ChannelNameLTE(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldChannelName, v))
}

// ChannelNameContains applies the Contains predicate on the "channel_name" field.
func ChannelNameContains(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldContains(FieldChannelName, v))
}

// ChannelNameHasPrefix applies the HasPrefix predicate on the "channel_name" field.
func ChannelNameHasPrefix(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldHasPrefix(FieldChannelName, v))
}

// ChannelNameHasSuffix applies the HasSuffix predicate on the "channel_name" field.
func ChannelNameHasSuffix(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldHasSuffix(FieldChannelName, v))
}

// ChannelNameEqualFold applies the EqualFold predicate on the "channel_name" field.
func ChannelNameEqualFold(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEqualFold(FieldChannelName, v))
}

// ChannelNameContainsFold applies the ContainsFold predicate on the "channel_name" field.
func ChannelNameContainsFold(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldContainsFold(FieldChannelName, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldContainsFold(FieldModelID, v))
}

// ReasoningEffortEQ applies the EQ predicate on the "reasoning_effort" field.
func ReasoningEffortEQ(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldReasoningEffort, v))
}

// ReasoningEffortNEQ applies the NEQ predicate on the "reasoning_effort" field.
func ReasoningEffortNEQ(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldReasoningEffort, v))
}

// ReasoningEffortIn applies the In predicate on the "reasoning_effort" field.
func ReasoningEffortIn(vs ...string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortNotIn applies the NotIn predicate on the "reasoning_effort" field.
func ReasoningEffortNotIn(vs ...string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortGT applies the GT predicate on the "reasoning_effort" field.
func ReasoningEffortGT(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldReasoningEffort, v))
}

// ReasoningEffortGTE applies the GTE predicate on the "reasoning_effort" field.
func ReasoningEffortGTE(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldReasoningEffort, v))
}

// ReasoningEffortLT applies the LT predicate on the "reasoning_effort" field.
func ReasoningEffortLT(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldReasoningEffort, v))
}

// ReasoningEffortLTE applies the LTE predicate on the "reasoning_effort" field.
func ReasoningEffortLTE(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldReasoningEffort, v))
}

// ReasoningEffortContains applies the Contains predicate on the "reasoning_effort" field.
func ReasoningEffortContains(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldContains(FieldReasoningEffort, v))
}

// ReasoningEffortHasPrefix applies the HasPrefix predicate on the "reasoning_effort" field.
func ReasoningEffortHasPrefix(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldHasPrefix(FieldReasoningEffort, v))
}

// ReasoningEffortHasSuffix applies the HasSuffix predicate on the "reasoning_effort" field.
func ReasoningEffortHasSuffix(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldHasSuffix(FieldReasoningEffort, v))
}

// ReasoningEffortEqualFold applies the EqualFold predicate on the "reasoning_effort" field.
func ReasoningEffortEqualFold(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEqualFold(FieldReasoningEffort, v))
}

// ReasoningEffortContainsFold applies the ContainsFold predicate on the "reasoning_effort" field.
func ReasoningEffortContainsFold(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldContainsFold(FieldReasoningEffort, v))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldTrigger, vs...))
}

// TriggerGT applies the GT predicate on the "trigger" field.
func TriggerGT(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldTrigger, v))
}

// TriggerGTE applies the GTE predicate on the "trigger" field.
func TriggerGTE(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldTrigger, v))
}

// TriggerLT applies the LT predicate on the "trigger" field.
func TriggerLT(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldTrigger, v))
}

// TriggerLTE applies the LTE predicate on the "trigger" field.
func TriggerLTE(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldTrigger, v))
}

// TriggerContains applies the Contains predicate on the "trigger" field.
func TriggerContains(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldContains(FieldTrigger, v))
}

// TriggerHasPrefix applies the HasPrefix predicate on the "trigger" field.
func TriggerHasPrefix(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldHasPrefix(FieldTrigger, v))
}

// TriggerHasSuffix applies the HasSuffix predicate on the "trigger" field.
func TriggerHasSuffix(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldHasSuffix(FieldTrigger, v))
}

// TriggerEqualFold applies the EqualFold predicate on the "trigger" field.
func TriggerEqualFold(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEqualFold(FieldTrigger, v))
}

// TriggerContainsFold applies the ContainsFold predicate on the "trigger" field.
func TriggerContainsFold(v string) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldContainsFold(FieldTrigger, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldStatus, vs...))
}

// TotalKeysEQ applies the EQ predicate on the "total_keys" field.
func TotalKeysEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldTotalKeys, v))
}

// TotalKeysNEQ applies the NEQ predicate on the "total_keys" field.
func TotalKeysNEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldTotalKeys, v))
}

// TotalKeysIn applies the In predicate on the "total_keys" field.
func TotalKeysIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldTotalKeys, vs...))
}

// TotalKeysNotIn applies the NotIn predicate on the "total_keys" field.
func TotalKeysNotIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldTotalKeys, vs...))
}

// TotalKeysGT applies the GT predicate on the "total_keys" field.
func TotalKeysGT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldTotalKeys, v))
}

// TotalKeysGTE applies the GTE predicate on the "total_keys" field.
func TotalKeysGTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldTotalKeys, v))
}

// TotalKeysLT applies the LT predicate on the "total_keys" field.
func TotalKeysLT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldTotalKeys, v))
}

// TotalKeysLTE applies the LTE predicate on the "total_keys" field.
func TotalKeysLTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldTotalKeys, v))
}

// SuccessKeysEQ applies the EQ predicate on the "success_keys" field.
func SuccessKeysEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldSuccessKeys, v))
}

// SuccessKeysNEQ applies the NEQ predicate on the "success_keys" field.
func SuccessKeysNEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldSuccessKeys, v))
}

// SuccessKeysIn applies the In predicate on the "success_keys" field.
func SuccessKeysIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldSuccessKeys, vs...))
}

// SuccessKeysNotIn applies the NotIn predicate on the "success_keys" field.
func SuccessKeysNotIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldSuccessKeys, vs...))
}

// SuccessKeysGT applies the GT predicate on the "success_keys" field.
func SuccessKeysGT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldSuccessKeys, v))
}

// SuccessKeysGTE applies the GTE predicate on the "success_keys" field.
func SuccessKeysGTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldSuccessKeys, v))
}

// SuccessKeysLT applies the LT predicate on the "success_keys" field.
func SuccessKeysLT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldSuccessKeys, v))
}

// SuccessKeysLTE applies the LTE predicate on the "success_keys" field.
func SuccessKeysLTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldSuccessKeys, v))
}

// FailedKeysEQ applies the EQ predicate on the "failed_keys" field.
func FailedKeysEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldFailedKeys, v))
}

// FailedKeysNEQ applies the NEQ predicate on the "failed_keys" field.
func FailedKeysNEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldFailedKeys, v))
}

// FailedKeysIn applies the In predicate on the "failed_keys" field.
func FailedKeysIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldFailedKeys, vs...))
}

// FailedKeysNotIn applies the NotIn predicate on the "failed_keys" field.
func FailedKeysNotIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldFailedKeys, vs...))
}

// FailedKeysGT applies the GT predicate on the "failed_keys" field.
func FailedKeysGT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldFailedKeys, v))
}

// FailedKeysGTE applies the GTE predicate on the "failed_keys" field.
func FailedKeysGTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldFailedKeys, v))
}

// FailedKeysLT applies the LT predicate on the "failed_keys" field.
func FailedKeysLT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldFailedKeys, v))
}

// FailedKeysLTE applies the LTE predicate on the "failed_keys" field.
func FailedKeysLTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldFailedKeys, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldLTE(FieldDurationMs, v))
}

// ResultsIsNil applies the IsNil predicate on the "results" field.
func ResultsIsNil() predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldIsNull(FieldResults))
}

// ResultsNotNil applies the NotNil predicate on the "results" field.
func ResultsNotNil() predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.FieldNotNull(FieldResults))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntelligenceRun) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntelligenceRun) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntelligenceRun) predicate.IntelligenceRun {
	return predicate.IntelligenceRun(sql.NotPredicates(p))
}
